### PR TITLE
Achieve feature parity with the Android SDK

### PR DESCRIPTION
**Pull request by mttcrsp**
In order to allow users of the library to customise the CMP user experience, the Android SDK exposes the consent string generation API and the vendor list download API. This PR is aimed at bringing that very same behaviour to the iOS SDK.

PS Thank you for your great work on this library! 👍

### CODE REVIEW

**Comment by lgironditmetaz** [comment]
Sorry for the late reply.

Do you have an example of a CMP user experience customization that would requires access to the vendor list manager?
We intentionally kept some components private such as the vendor list manager because we consider them as implementation detail (and putting them public will make future refactoring harder), but also because the parsed vendor list can be retrieved through a public API.

For the `CMPConsentString` extension, it could be useful to put some (or all) methods public for easier consent string manipulation (if you want to use a custom UI for instance), but in this case we need to make them available for Objective-C as well (since Swift 4 as removed the automatic `@objc` inference).

**Comment by mttcrsp** [comment]
> Do you have an example of a CMP user experience customization that would requires access to the vendor list manager?

I'll take a step back for a second. While integrating the library I wanted to perform some additional UI customisation I needed to perform some additional customisation. The CMPConsentManager is a really nice utility and really simplifies interaction with the SDK by limiting its API surface. However, while integrating the SDK I found that it significantly limited advanced use cases and made some UX specs impossible to implement.

To answer your question, I thought it would be nice to expose the vendor list manager because it allows users of the library to have full control over the whole vendor list download process, including how loading times and network errors are handled from a UX perspective, and be potentially be able not to depend on `CMPConsentManager`.

Anyway, I fully understand if you prefer to disallow this in order to reduce the maintenance burden associated with the project.

> But in this case we need to make them available for Objective-C as well (since Swift 4 as removed the automatic `@objc` inference).

You are absolutely right, I'll fix this ASAP.

**Comment by mttcrsp** [comment]
I resolved a merge conflict and implemented the requested `@objc` related changes.

Having noticed that most of the project is exposing all public classes and methods to the ObjC runtime I prepared a new PR that adopts the `@objcMembers` annotation to appropriated classes. This should prevent the mistake I made from being repeated in the future as it will automatically mark all ObjC compatible properties as `@objc`. I'll open this additional PR if/when this one gets merged.

**Comment by lgironditmetaz** [comment]
Thanks for the PR.
I have only done a partial merge for now, only `CMPConsentString` utils methods are public.

**Pull request merged**
